<?php
$GLOBALS['PHP_DIR'] = __DIR__ . DIRECTORY_SEPARATOR;
$GLOBALS['CSS_DIR'] = $GLOBALS['PHP_DIR']."css" . DIRECTORY_SEPARATOR;
$GLOBALS['PDO_WRAPPER'] = $GLOBALS['PHP_DIR'] . "class/pdo_wrapper/PdoWrapper.php";