<?php
$GLOBALS['PROJECT_DIR'] = DIRECTORY_SEPARATOR . "web3" . DIRECTORY_SEPARATOR . "L2_Web_Projet_3" . DIRECTORY_SEPARATOR;
$GLOBALS['PHP_DIR'] = __DIR__ . DIRECTORY_SEPARATOR;
$GLOBALS['CLASS_DIR'] = $GLOBALS['PROJECT_DIR'] . "class" . DIRECTORY_SEPARATOR;
$GLOBALS['CSS_DIR'] = $GLOBALS['PROJECT_DIR'] . "css" . DIRECTORY_SEPARATOR;
$GLOBALS['JS_DIR'] = $GLOBALS['PROJECT_DIR'] . "js" . DIRECTORY_SEPARATOR;
$GLOBALS['PDO_WRAPPER'] = $GLOBALS['PHP_DIR'] . "class/pdo_wrapper/PdoWrapper.php";
$GLOBALS['POSTER_DIR'] = $GLOBALS['PROJECT_DIR'] . "uploads" . DIRECTORY_SEPARATOR . "posters" . DIRECTORY_SEPARATOR;
$GLOBALS['PEOPLES_DIR'] = $GLOBALS['PROJECT_DIR'] . "uploads" . DIRECTORY_SEPARATOR . "peoples" . DIRECTORY_SEPARATOR;
$GLOBALS['API_DIR'] = $GLOBALS['PROJECT_DIR'] . "api" . DIRECTORY_SEPARATOR;
$GLOBALS['LOCALIZATION_DIR'] = $GLOBALS['PHP_DIR'] . "localization" . DIRECTORY_SEPARATOR;

$GLOBALS['languages-list'] = array(
    '1' => 'FR',
    '2' => 'EN',
    '3' => 'ES',
    '4' => 'DE');

$GLOBALS['dateFormats'] = array(
    'FR' => 'd/m/Y',
    'EN' => 'm/d/Y',
    'ES' => 'd-m-Y',
    'DE' => 'd.m.Y');